parameters:
    pilebones_logstash.monolog.logstash_handler.class: Pilebones\LogstashBundle\Monolog\Handler\LogstashHandler

services:
    pilebones_logstash.monolog.logstash_handler:
        class: "%pilebones_logstash.monolog.logstash_handler.class%"
        arguments: ["@request_stack", "%pilebones_logstash.logstash_address%", 100, true, ~ ]
        calls:
            - [setFormatter, [ @monolog.formatter.json ]]
